name: Docker CI

on:
  push:
    tags: [ "*" ]
    branches: [ "main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: asithan/ballerina-dev # list of Docker images to use as base name for tags
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ contains(github.ref, 'refs/tags/') }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            BASE_IMG_VARIANT=ubuntu
            BALLERINA_DEB_URL=https://dist.ballerina.io/downloads/swan-lake-alpha4/ballerina-linux-installer-x64-swan-lake-alpha4.deb
            BALLERINA_VSIX_URL=https://github.com/ballerina-platform/plugin-vscode/releases/download/vswan-lake-alpha4/ballerina-swan-lake-alpha4.vsix
      -
        name: Image digest
        run: echo ${{ steps.docker.outputs.digest }}